# https://github.com/dart-lang/build/blob/7002c666513db0fa29756b6ed39c048732b04297/docs/faq.md
# https://github.com/dart-lang/build/tree/7002c666513db0fa29756b6ed39c048732b04297/build_web_compilers

targets:
  $default:
    builders:
      angular_components|scss_builder:
        enabled: true
      build_web_compilers:entrypoint:
        # These are globs for the entrypoints you want to compile.
        generate_for:
          - web/main.dart
        options:
          compiler: dart2js
          dart2js_args:
            - -O3
            - -DAPI_ORIGIN=https://mnemosyne.zxteam.org
