name: zxteamorg_mnemosyne
description: CryptoPay's Dashboard Audit web app that uses AngularDart
version: 0.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  angular: ^6.0.0-alpha
  angular_components: ^1.0.2
  bootstrap_sass: ^4.5.0

dev_dependencies:
  angular_test: ^2.3.1
  build_runner: ^1.5.1
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  sass_builder: ^2.1.3
  test: ^1.6.4
