name: zxteamorg_mnemosyne
description: Mnemosyne Web Application that uses AngularDart
version: 0.0.1

environment:
  sdk: ">=2.2.0 <3.0.0"

dependencies:
  angular: ^6.0.1
  angular_components: ^1.0.2
  angular_forms: ^3.0.0
  angular_router: ^2.0.0
  bootstrap_sass: ^4.5.0
  convert: ^2.1.1

dev_dependencies:
  angular_test: ^2.3.1
  build_runner: ^1.5.1
  build_test: ^0.10.8
  build_web_compilers: ^2.1.0
  test: ^1.6.4
